import DotsBackground from './DotsBg.svg?react'
import TriadSpaceBackground from './TriadSpaceBg.svg?react'
import TilesDarkBackground from './TilesDarkBg.svg?react'
import MapPathCorner from './MapPathCorner.svg?react'
import MapPathVertical from './MapPathVertical.svg?react'
import BombCoin from './BombCoin.svg?react'
import DollarCoin from './DollarCoin.svg?react'
import EyeCoin from './EyeCoin.svg?react'
import GoldCoin from './GoldCoin.svg?react'
import MagnetCoin from './MagnetCoin.svg?react'
import RocketCoin from './RocketCoin.svg?react'
import UfoCoin from './UfoCoin.svg?react'
import HeroGood from './HeroGood.svg?react'
import HeroHalfOpen from './HeroHalfOpen.svg?react'
import HeroOpen from './HeroOpen.svg?react'
import HeroSad from './HeroSad.svg?react'
import HeroSad2 from './HeroSad2.svg?react'
import DialogueCloud from './DialogueCloud.svg?react'
import CoinsIlustration from './CoinsIlustration.svg?react'
import SquaresPattern from './SquaresPattern.svg?react'

export { DotsBackground, MapPathCorner, DialogueCloud, SquaresPattern, CoinsIlustration, MapPathVertical, TriadSpaceBackground, TilesDarkBackground, BombCoin, DollarCoin, EyeCoin, GoldCoin, MagnetCoin, RocketCoin, UfoCoin, HeroGood, HeroHalfOpen, HeroOpen, HeroSad, HeroSad2 }